name: Linter

on:
  pull_request:
    branches: [ main ]
  push:
    paths:
      - 'assets/theme.js'
      - 'assets/theme.css'
  # workflow_run:
  #   workflows: [ Theme Check ]
  #   types: [ completed ]

jobs:
  linting:
    name: GH Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JS/CSS linting
        uses: github/super-linter/slim@v4.9.4
        env:
          LINTER_RULES_PATH: /
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_HTML: true
          FILTER_REGEX_EXCLUDE: (assets/.*\.css)
          GITHUB_TOKEN: ${{ github.token }}
          DEFAULT_BRANCH: main
