name: Shopify - Theme Check
on: [ push ]

jobs:
  shopify-theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Theme Check and Liquid linting
        uses: shopify/theme-check-action@v1.2.2
        with:
          # flags: ''
          token: ${{ github.token }}
          base: main
