name: Shopify -  Lighthouse CI
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  shopify-lighthouse-ci:
    name: Lighthouse
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: shopify/lighthouse-ci-action@v1
        with:
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_PASSWORD }}