name: Shopify - Theme Check
on:
  push: 
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  shopify-theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Theme Check and Liquid linting
        uses: shopify/theme-check-action@v1.2.2
        # keeping the below commented out until this issue is resolved:
        # https://github.com/Shopify/theme-check-action/issues/13
        with:
          # flags: ''
          token: ${{ github.token }}
          base: main
